x-vars:
  OPENSEARCH_CLUSTER_NAME: &OPENSEARCH_CLUSTER_NAME "opensearch-cluster"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: &OPENSEARCH_INITIAL_ADMIN_PASSWORD "F50UjL0vRYRR8o&*"

services:
  openserarch-node1:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node1
    environment:
      cluster.name: *OPENSEARCH_CLUSTER_NAME
      node.name: opensearch-node1
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: '-Xms1024m -Xms1024m'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: *OPENSEARCH_INITIAL_ADMIN_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node2
    environment:
      cluster.name: *OPENSEARCH_CLUSTER_NAME
      node.name: opensearch-node2
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: '-Xms1024m -Xms1024m'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: *OPENSEARCH_INITIAL_ADMIN_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200", "https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net: